### PR TITLE
Release 2023.7

### PR DESCRIPTION
**Pull request by lizgehret**
Adds jupyter packages back into core distribution.

### CODE REVIEW

**Comment by ebolyen** [comment]
Maybe just put jupyter (a metapackage itself) on it's own? that really ought to have worked (it's no different than numpy or whatever).

**Comment by ebolyen** [comment]
Oh, no we need to add all of the names into the digraph before looking at edges, as these are actually not connected by any of our plugins, unlike the other packages, which are dependencies of at least 1 plugin.

**Comment by lizgehret** [comment]
> Oh, no we need to add all of the names into the digraph before looking at edges, as these are actually not connected by any of our plugins, unlike the other packages, which are dependencies of at least 1 plugin.

Oh yeah, that's right. Our DAG won't keep anything that's not connected to at least one other package. Should we modify the `make_dag` script to keep any packages that are listed in the given seed-env file, since we'll be the only ones modifying that? Or is there an easier way to handle?

**Comment by ebolyen** [comment]
Yeah I think that's what we need to do. Just sticking them in the DAG ought to be enough, because then we'll have a node with no-edges to traverse which should satisfy the rest of the code just fine. Feel free to make that change on this branch (otherwise we have to rebase this PR to get the updates).

**Comment by lizgehret** [comment]
> Yeah I think that's what we need to do. Just sticking them in the DAG ought to be enough, because then we'll have a node with no-edges to traverse which should satisfy the rest of the code just fine. Feel free to make that change on this branch (otherwise we have to rebase this PR to get the updates).

@ebolyen check out the summary, I think that's what we want. For the jupyter packages I added, I just pulled what was in our last release environment file - but wondering if we can get away with fewer packages, depending on what people need? Is it just jupyter notebook we want people to have? Or any other jupyter extensions?

**Comment by ebolyen** [comment]
I'm not actually sure if these are all of the jupyter packages or not, hence the preference for `jupyter=<ver>` since that metapackage will be whatever is needed to do the usual thing.

But looks like it solved and built just fine! 
We may need to test manually that `jupyter notebook` runs like we expect.

**Comment by lizgehret** [comment]
> I'm not actually sure if these are all of the jupyter packages or not, hence the preference for `jupyter=<ver>` since that metapackage will be whatever is needed to do the usual thing.
> 
> But looks like it solved and built just fine! We may need to test manually that `jupyter notebook` runs like we expect.

I tested this out locally, and we actually need the `notebook` package in order for jupyter notebook to be available. When I added `notebook=7.0.2` (latest release on conda-forge) to my local 2023.7 environment, it solved successfully and jupyter notebook worked as expected locally.

I'm going to remove all of the jupyter* packages from the seed environment file, and replace them with `notebook=7.0.2` - that will pull in all of the required jupyter* packages for notebook specifically.

**Comment by lizgehret** [comment]
Turns out [we have a max pin in the framework tests](https://github.com/qiime2/qiime2/pull/703) for notebook <7, so I tested locally and 6.5.5 solves and has expected behavior. Didn't catch this locally because the version pin is only for the framework tests, not the actual build. Sad to re-run these all over again lol but this environment should solve this time around, and tests should all work. It's really cool to see this iterative process in action though, and it's so easy to debug!

**Pull request merged**
