### PR TITLE
LANG: python 3.10 update (metagenome)

### PR DESCRIPTION
**Pull request by lizgehret**

### CODE REVIEW

**Comment by ebolyen** [comment]
This is probably relevant: https://github.com/qiime2/action-library-packaging/blob/beta/src/alp/cbc.py#L1-L3

**Comment by lizgehret** [comment]
Okay so I think main conflicts here are from the busco pin that's in q2-moshpit.
Paired PR to relax that pin: https://github.com/bokulich-lab/q2-moshpit/pull/204

We'll see how things shake out from here!

**Comment by lizgehret** [comment]
Okay so this is the current source of the issue from [busco's bioconda recipe](https://github.com/bioconda/bioconda-recipes/blob/89b5475f6f128ac7017573281b2c3a336112b2b8/recipes/busco/meta.yaml#L50). I think this has since been resolved with the latest release of SEPP, so I'm going to open an issue to remove this pin. We'll just have to hope for the best in terms of this getting resolved within the next month.

**Comment by lizgehret** [comment]
I've opened a PR on bioconda, so fingers crossed this will get resolved within the next couple of weeks.
https://github.com/bioconda/bioconda-recipes/pull/50711

**Pull request merged**
