### PR TITLE
DEP: sklearn 1.3.1

### PR DESCRIPTION
**Pull request by ebolyen**
Let's see what breaks.

### CODE REVIEW

**Comment by ebolyen** [comment]
So, the `pillow` library is getting pulled from the `defaults` channel instead of `conda-forge`. The system seems to be preferring the newer version (which isn't binary compatible). Either we need a flag somewhere to stop that, or there's something intractable and conda is doing it's best.

**Comment by ebolyen** [comment]
No dice.

**Comment by ebolyen** [comment]
Running this again since we have new conda solvers, maybe it will help?

**Comment by gregcaporaso** [comment]
I tired that locally yesterday, and it didn't seem to, but curious to see what happens here. 🤞

**Comment by lizgehret** [comment]
Once this is working, we need to take a look at [this sample-classifier PR](https://github.com/qiime2/q2-sample-classifier/pull/218) that addresses the deprecated grid_scores_ attr in sklearn >= 1.2

**Comment by gregcaporaso** [comment]
replacing with #164

**Pull request closed without merging**
