### PR TITLE
NEW: adds q2-fondue to the shotgun distro

### PR DESCRIPTION
**Pull request by misialq**
It would be lovely to have fondue there for dataset fetching from the SRA. Not sure whether we also want that in the _amplicon_ distro?

### CODE REVIEW

**Comment by lizgehret** [comment]
Great idea @misialq - I certainly like the idea of adding to amplicon as well, but I do wonder how the additional dependencies will play with the rest of the ecosystem. Maybe this is a good topic to discuss in our joint meeting next week?

**Comment by misialq** [comment]
Sounds great, let's discuss! 👏

**Comment by lizgehret** [comment]
cc @gregcaporaso

**Comment by lizgehret** [comment]
I'll go ahead and merge this so that this is ready when we do a prepare on shotgun, thanks @misialq!

**Pull request merged**
