### PR TITLE
LANG: python 3.10 update (amplicon)

### LINKED ISSUE #88: DEP: q2-fragment-insertion can't be upgraded to Python 3.10, due to pinned SEPP dependency on Python <=3.9
[Here's](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/sepp/meta.yaml#L24) the relevant pin. This will need to be addressed for q2-fragment-insertion to stay in the amplicon distribution when QIIME 2 transitions its Python version to 3.10 (planned for the 2024.10 release, which is currently scheduled for 2 October 2024).

### PR DESCRIPTION
**Pull request by lizgehret**
local install of all external dependencies was successful, so now it's time to see what breaks!

### CODE REVIEW

**Comment by lizgehret** [comment]
Okay so current issue here is from q2-fragment-insertion's [pin of `dendropy`](https://github.com/qiime2/q2-fragment-insertion/blob/80d17ccf8d29f1fbdd25684a71209e45f4882ccb/ci/recipe/meta.yaml#L30). This pin is because `sepp` depends on an old version of `dendropy` (because it [imports a private function that no longer exists](https://github.com/smirarab/sepp/blob/66cf22cfb9ca22ed9e9074984018d099617b3c6a/sepp/tree.py#L25) in the current versions) which is (of course) not compatible with python 3.10. We'll need to figure out what to do about this because this blocks q2-fragment-insertion from being included in the 3.10 update.

**Comment by lizgehret** [comment]
Okay so it looks like the [latest version of sepp](https://github.com/smirarab/sepp/issues/125#issuecomment-2316392621) resolved this issue (less than two weeks ago!) and builds are now up on bioconda. Paired [PR in fragment-insertion](https://github.com/qiime2/q2-fragment-insertion/pull/90) that removes this pin - we'll see if this works!

**Comment by lizgehret** [comment]
Another [paired PR in alignment](https://github.com/qiime2/q2-alignment/pull/85) - this punts the mafft pin back to alignment's recipe, using the min pin previously present

**Comment by ebolyen** [comment]
Wow, it looks like it practically worked!

Now that you have a solve, I would recommend putting mafft back into the seed env with the new pin (whatever that ended up being), and also maybe we should do the same for dendropy? That way we can control all of these in one place.

(I realize that you needed the >= operator to try and solve for mafft, which wouldn't have worked in the seed env... probably?)

**Comment by lizgehret** [comment]
PR to address test failures in vsearch (very minor): https://github.com/qiime2/q2-vsearch/pull/99

I'll try adding mafft as a min pin in the seed env @ebolyen - conda's docs do state that [pin ranges are supported](https://conda.io/projects/conda/en/latest/user-guide/concepts/pkg-search.html#standard-specification), and that might be better for this situation. I'm debating between pinning sepp and dendropy, since sepp is the root offender. Now that I've written that out, I think I'm leaning towards a min pin for sepp - that way we're just ensuring we have at least the build that's fixed that old dendropy dependency.

**EDIT**: so even though conda supports pin ranges, it doesn't seem to be easily compatible with the jinja templating for package versions (within each individual package) - so i've just set the pins for mafft and sepp, and we'll just fuss with them if/when they stop working.

**Comment by lizgehret** [comment]
We've got a working build! 🥳

**Pull request merged**
